# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170529_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.TopModel'),
        ),
    ]
