# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontauth', '0002_auto_20170603_2210'),
        ('article', '0004_auto_20170603_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleModel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontauth.FrontUserModel')),
            ],
        ),
    ]
