# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontUserModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
