# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontusermodel',
            old_name='password',
            new_name='_password',
        ),
    ]
